### ISSUE TITLE
Les fichiers .geojson devraient avoir 'application/vnd.geo+json' comme Content-Type

### ISSUE THREAD

**Issue by oncletom** [datalocale/ckanext-datalocale#5]
Ou à défaut en `application/json` — via https://en.wikipedia.org/wiki/JSON et https://en.wikipedia.org/wiki/GeoJSON

Ils sont aujourd'hui servis en `Content-Type: application/octet-stream`.

Via https://www.data.gouv.fr/fr/datasets/aires-de-covoiturage-en-gironde-1/

![image](https://user-images.githubusercontent.com/138627/28533979-ea9f6fde-7096-11e7-93a1-8fc908eb00ab.png)

**Comment by dlax** [comment]
Le type MIME n'est pas bien "deviné" à l'upload (par la bibliothèque standard Python). J'ai corrigé la donnée mais il faudrait faire en sorte de bien deviner.

Ce n'est pas du ressort de ce projet, j'ai crée un ticket sur le "bon" projet : https://www.cubicweb.org/ticket/17092141
